# Generated by Django 6.0 on 2026-01-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='food/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('food_item_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemsubcategory'),
        ),
    ]
