# Generated by Django 6.0 on 2026-01-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('calories', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemCategory',
            fields=[
                ('food_item_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.ImageField(upload_to='food_images/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemSubCategory',
            fields=[
                ('sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=255)),
                ('food_item_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.fooditemcategory')),
            ],
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='menu.fooditemsubcategory'),
        ),
    ]
