# Generated by Django 6.0 on 2026-01-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditemimage',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='fooditemsubcategory',
            name='food_item_cat',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='FoodItemImage',
        ),
        migrations.DeleteModel(
            name='FoodItemCategory',
        ),
        migrations.DeleteModel(
            name='FoodItemSubCategory',
        ),
    ]
